<#
.SYNOPSIS
  Create a FULL updated project ZIP (client + server + configs), excluding heavy junk.

.DESCRIPTION
  Copies the whole `event-booking-app` folder (parent of this `scripts` folder) to a temp
  staging area using robocopy, excluding:
    node_modules, dist, build, .git, .cache, .next, coverage, .turbo, .vite, tmp, temp, __pycache__
  and *.log files.

  Output defaults to your Downloads folder with a timestamp so it is never empty if the script completes.

.PARAMETER RepoRoot
  Path to the `event-booking-app` folder (contains `client`, `server`, `scripts`). Default: parent of `scripts`.

.PARAMETER OutZip
  Full path to the .zip file to create. Default: ~\Downloads\event-booking-app-FULL-UPDATED-YYYYMMDD-HHmm.zip
#>
[CmdletBinding()]
param(
  [string] $RepoRoot = "",
  [string] $OutZip = ""
)

$ErrorActionPreference = "Stop"

$scripts = $PSScriptRoot
if ($RepoRoot -and $RepoRoot.Trim().Length -gt 0) {
  $src = (Resolve-Path -LiteralPath $RepoRoot).Path
} else {
  $src = (Resolve-Path -LiteralPath (Join-Path (Split-Path -Parent $scripts) ".")).Path
}

if (-not (Test-Path -LiteralPath (Join-Path $src "client"))) {
  throw "RepoRoot does not look like event-booking-app (missing client folder): $src"
}

$folderName = Split-Path -Leaf $src
if (-not $OutZip -or $OutZip.Trim().Length -eq 0) {
  $stamp = Get-Date -Format "yyyyMMdd-HHmm"
  $OutZip = Join-Path $env:USERPROFILE "Downloads\event-booking-app-FULL-UPDATED-$stamp.zip"
} else {
  $OutZip = $ExecutionContext.SessionState.Path.GetUnresolvedProviderPathFromPSPath($OutZip)
}

$staging = Join-Path $env:TEMP ("eb-full-" + [Guid]::NewGuid().ToString("n"))
$inner = Join-Path $staging $folderName
New-Item -ItemType Directory -Path $inner -Force | Out-Null

Write-Host "Source:  $src"
Write-Host "Staging: $inner"
Write-Host "OutZip:  $OutZip"

$robArgs = @(
  $src, $inner, "/E", "/NFL", "/NDL", "/NJH", "/NJS", "/XF", "*.log",
  "/XD", "node_modules", "dist", "build", ".git", ".cache", ".next", "coverage",
  ".turbo", ".vite", "tmp", "temp", "__pycache__"
)
& robocopy.exe @robArgs | Out-Null
$code = $LASTEXITCODE
if ($code -ge 8) {
  throw "robocopy failed with exit code $code"
}

# Sanity: must have content
$childCount = (Get-ChildItem -LiteralPath $inner -Force | Measure-Object).Count
if ($childCount -lt 1) {
  throw "Staging folder is empty — aborting so we do not create a 0-byte zip."
}

$readme = @'
# Full project export (after extract)

This ZIP omits `node_modules`, `dist`, and other generated folders to keep size reasonable.

## Install

```powershell
cd client
npm install
```

```powershell
cd ..\server
npm install
```

Run client and server per your original project README.

Generated by Export-FullProjectZip.ps1
'@
Set-Content -LiteralPath (Join-Path $inner "ZIP_EXPORT_README.txt") -Value $readme -Encoding UTF8

if (Test-Path -LiteralPath $OutZip) {
  Remove-Item -LiteralPath $OutZip -Force
}

# One root folder inside the zip (clean extract)
Compress-Archive -LiteralPath $inner -DestinationPath $OutZip -CompressionLevel Optimal -Force

Remove-Item -LiteralPath $staging -Recurse -Force

$info = Get-Item -LiteralPath $OutZip
if ($info.Length -eq 0) {
  throw "ZIP was created but size is 0 bytes — check disk space and paths."
}

Write-Host ""
Write-Host "SUCCESS: $($info.FullName)"
Write-Host "Size:    $($info.Length) bytes ($([math]::Round($info.Length/1MB, 2)) MB)"
